name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger pipeline on pull requests to the main branch

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0  # Use .NET 8 (adjust as needed)
      
      # Install dependencies and build
      - name: Install dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore
      
      # Run tests
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

  deploy:
    name: Deploy to Docker Hub
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # Only deploy from main branch

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t your-dockerhub-username/taskservice:latest .
          docker push your-dockerhub-username/taskservice:latest
